### ISSUE TITLE
Use git submodules for data

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/sql#1]
This requires the creation of a data repo

**Comment by gaand** [comment]
@jrhorn424 I've changed my mind.  I don't think this is a good idea.  If you disagree, please reopen.

**Comment by jrhorn424** [comment]
I'd certainly be interested in talking about it, but I'm generally not a fan of submodules for sharing things, more for freezing dependencies.

So, yeah, don't use it? :smile:
