### ISSUE TITLE
Use versioned links for documentation, rather than `current`.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/sql#18]
Align with version of PostgreSQL installed in MAC OS X from brew.

**Comment by BenGitsCode** [comment]
Still missing some.

It looks like all documentation links are set to current (9.6 atm) for postgres documentation.

**Comment by BenGitsCode** [comment]
Still missing some.

It looks like all documentation links are set to current (9.6 atm) for postgres documentation.

**Comment by BenGitsCode** [comment]
Still missing some.

It looks like all documentation links are set to current (9.6 atm) for postgres documentation.
