### ISSUE TITLE
Lead consultant?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/sql#19]
I understand the change from instructor -> consultant. But why add 'lead consultant' @gaand ? Seems like we lose flexibility that way...

**Comment by gaand** [comment]
I meant the consultant leading.  I'm happy for alternate wording.  What would you like to call the consultant leading a talk?

**Comment by payne-chris-r** [comment]
`consultant leading`?

**Comment by gaand** [comment]
@payne-chris-r and I agreed on 

`following the consultant's lead`
