### ISSUE TITLE
Maybe kick things off with a question?

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/sql#2]
e.g. 
"We've been talking about Rails... why are we suddenly talking about databases?"

Context, scaffolding, etc etc.

**Comment by GA-MEB** [comment]
Maybe also contextualize the SQL lesson vis-a-vis learning Rails?
"We're going to learn SQL not because you need to write a lot of SQL to build a Rails application - you don't - but because your Rails app will be manipulating SQL databases behind the scenes as you do things, and it's important to be able to understand what it's doing. It's also important for debugging, since you might need to take a look into the data tables underlying your application when chasing down an error."

**Comment by gaand** [comment]
@MattB-GA-Boston Please see 992d2974d6de61375a788d488cf8a7f33bb42de8 and close or expand upon this issue.  Thanks.
